version: 2.1

jobs:
  lint:
    docker:
      - image: node:14.15.4
    steps:
      - checkout
      - restore_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
      - run: yarn install --check-files
      - save_cache:
          key: v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths:
            - node_modules
      - run: yarn run test:compile
      - run: yarn run lint

workflows:
  build:
    jobs:
      - lint
